# Generated by Django 5.2.6 on 2025-09-07 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0002_alter_student_current_class_alter_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('class', 'Class Report'), ('performance', 'Performance Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('parameters', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_students', models.IntegerField()),
                ('pass_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_subjects', models.IntegerField()),
                ('rank_in_class', models.IntegerField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
